(in-package :ccl)

(defparameter *all-EWQLSO-files* '(#p"/Brass/2 Trumpets/1 Long/F 2TP Mute Sus.nki"
                                   #p"/Brass/2 Trumpets/1 Long/F 2TP Portato.nki"
                                   #p"/Brass/2 Trumpets/1 Long/F 2TP QLeg RR.nki"
                                   #p"/Brass/2 Trumpets/1 Long/F 2TP QLeg.nki"
                                   #p"/Brass/2 Trumpets/1 Long/F 2TP Sus.nki"
                                   #p"/Brass/2 Trumpets/2 Short/F 2TP Marc.nki"
                                   #p"/Brass/2 Trumpets/2 Short/F 2TP Mute Stac RR x6.nki"
                                   #p"/Brass/2 Trumpets/2 Short/F 2TP Mute Stac RR.nki"
                                   #p"/Brass/2 Trumpets/2 Short/F 2TP Repetitions.nki"
                                   #p"/Brass/2 Trumpets/2 Short/F 2TP Stac RR x4.nki"
                                   #p"/Brass/2 Trumpets/2 Short/F 2TP Stac RR x8.nki"
                                   #p"/Brass/2 Trumpets/3 Effects/F 2TP 1sec Cres.nki"
                                   #p"/Brass/2 Trumpets/3 Effects/F 2TP 2sec Cres.nki"
                                   #p"/Brass/2 Trumpets/3 Effects/F 2TP Arp FX.nki"
                                   #p"/Brass/2 Trumpets/3 Effects/F 2TP Mute Cres Fltr.nki"
                                   #p"/Brass/2 Trumpets/3 Effects/F 2TP Mute Fltr Cres Fst.nki"
                                   #p"/Brass/2 Trumpets/3 Effects/F 2TP Mute Rip.nki"
                                   #p"/Brass/2 Trumpets/3 Effects/F 2TP Trill HT.nki"
                                   #p"/Brass/2 Trumpets/3 Effects/F 2TP Trill WT.nki"
                                   #p"/Brass/2 Trumpets/4 ModXfd/F 2TP Mute Sus DXF.nki"
                                   #p"/Brass/2 Trumpets/4 ModXfd/F 2TP QLeg DXF RR.nki"
                                   #p"/Brass/2 Trumpets/4 ModXfd/F 2TP QLeg DXF slud vs.nki"
                                   #p"/Brass/2 Trumpets/4 ModXfd/F 2TP QLeg DXF.nki"
                                   #p"/Brass/2 Trumpets/4 ModXfd/F 2TP Sus Acc MOD.nki"
                                   #p"/Brass/2 Trumpets/4 ModXfd/F 2TP Sus DXF Acc Vel.nki"
                                   #p"/Brass/2 Trumpets/4 ModXfd/F 2TP Sus DXF.nki"
                                   #p"/Brass/2 Trumpets/5 Keysw/F 2TP KS Cres C0-D#0.nki"
                                   #p"/Brass/2 Trumpets/5 Keysw/F 2TP KS Sus C0-B0.nki"

                                   #p"/Brass/3 Wagner Tuben/1 Long/F 3WT Big Sus.nki"
                                   #p"/Brass/3 Wagner Tuben/1 Long/F 3WT sus PORT.nki"
                                   #p"/Brass/3 Wagner Tuben/3 Effects/F 3WT rip.nki"
                                   #p"/Brass/3 Wagner Tuben/4 ModXfd/F 3WT sus x-FADE 2-WAY.nki"
                                   #p"/Brass/4 Trombones/1 Long/F 4TB Forte Piano.nki"
                                   #p"/Brass/4 Trombones/1 Long/F 4TB Mute Sus.nki"
                                   #p"/Brass/4 Trombones/1 Long/F 4TB Portato.nki"
                                   #p"/Brass/4 Trombones/1 Long/F 4TB QLeg RR.nki"
                                   #p"/Brass/4 Trombones/1 Long/F 4TB QLeg.nki"
                                   #p"/Brass/4 Trombones/1 Long/F 4TB Sus.nki"
                                   #p"/Brass/4 Trombones/2 Short/F 4TB Marc S Accent.nki"
                                   #p"/Brass/4 Trombones/2 Short/F 4TB Marc Short.nki"
                                   #p"/Brass/4 Trombones/2 Short/F 4TB Marc.nki"
                                   #p"/Brass/4 Trombones/2 Short/F 4TB Mute Stac RR x6.nki"
                                   #p"/Brass/4 Trombones/2 Short/F 4TB Mute Stac RR.nki"
                                   #p"/Brass/4 Trombones/2 Short/F 4TB Stac RR x3.nki"
                                   #p"/Brass/4 Trombones/2 Short/F 4TB Stac.nki"
                                   #p"/Brass/4 Trombones/3 Effects/F 4TB 1Sec Cres.nki"
                                   #p"/Brass/4 Trombones/3 Effects/F 4TB 2Sec Cres.nki"
                                   #p"/Brass/4 Trombones/3 Effects/F 4TB 3Sec Cres.nki"
                                   #p"/Brass/4 Trombones/3 Effects/F 4TB Bn Dn HT.nki"
                                   #p"/Brass/4 Trombones/3 Effects/F 4TB Clusters.nki"
                                   #p"/Brass/4 Trombones/3 Effects/F 4TB Flutter.nki"
                                   #p"/Brass/4 Trombones/3 Effects/F 4TB Forte Piano.nki"
                                   #p"/Brass/4 Trombones/3 Effects/F 4TB Mute Cres Fltr.nki"
                                   #p"/Brass/4 Trombones/3 Effects/F 4TB Mute Fltr Cres Fst.nki"
                                   #p"/Brass/4 Trombones/4 ModXfd/F 4TB Marc S Sus X-Fade.nki"
                                   #p"/Brass/4 Trombones/4 ModXfd/F 4TB Mute Sus DXF.nki"
                                   #p"/Brass/4 Trombones/4 ModXfd/F 4TB QLeg DXF RR.nki"
                                   #p"/Brass/4 Trombones/4 ModXfd/F 4TB QLeg DXF.nki"
                                   #p"/Brass/4 Trombones/4 ModXfd/F 4TB Sus ACC DXF.nki"
                                   #p"/Brass/4 Trombones/4 ModXfd/F 4TB Sus accent Mod.nki"
                                   #p"/Brass/4 Trombones/4 ModXfd/F 4TB Sus DXF.nki"
                                   #p"/Brass/4 Trombones/5 Keysw/F 4TB KS Cres C0-D#0.nki"
                                   #p"/Brass/4 Trombones/5 Keysw/F 4TB KS Sus C5-B5.nki"

                                   #p"/Brass/4 Trumpets/1 Long/F 4TP Forte Piano.nki"
                                   #p"/Brass/4 Trumpets/1 Long/F 4TP Sfz.nki"
                                   #p"/Brass/4 Trumpets/1 Long/F 4TP Sus.nki"
                                   #p"/Brass/4 Trumpets/2 Short/F 4TP Stac RR x3.nki"
                                   #p"/Brass/4 Trumpets/2 Short/F 4TP Stac.nki"
                                   #p"/Brass/4 Trumpets/3 Effects/F 4TP Crec.nki"
                                   #p"/Brass/4 Trumpets/4 ModXfd/F 4TP Sus ACC VEL DXF.nki"
                                   #p"/Brass/4 Trumpets/4 ModXfd/F 4TP Sus accent Mod.nki"
                                   #p"/Brass/4 Trumpets/4 ModXfd/F 4TP Sus DXF Leg.nki"
                                   #p"/Brass/4 Trumpets/4 ModXfd/F 4TP Sus DXF.nki"

                                   #p"/Brass/6 French Horns/1 Long/F 6FH 3SEC Marc.nki"
                                   #p"/Brass/6 French Horns/1 Long/F 6FH Mute Sus.nki"
                                   #p"/Brass/6 French Horns/1 Long/F 6FH Portato.nki"
                                   #p"/Brass/6 French Horns/1 Long/F 6FH QLeg RR.nki"
                                   #p"/Brass/6 French Horns/1 Long/F 6FH QLeg.nki"
                                   #p"/Brass/6 French Horns/1 Long/f 6FH Sfz.nki"
                                   #p"/Brass/6 French Horns/1 Long/F 6FH Stop fast.nki"
                                   #p"/Brass/6 French Horns/1 Long/F 6FH Stop.nki"
                                   #p"/Brass/6 French Horns/1 Long/F 6FH Sus 4 Lay Smooth.nki"
                                   #p"/Brass/6 French Horns/1 Long/F 6FH Sus 4 lay.nki"
                                   #p"/Brass/6 French Horns/1 Long/F 6FH Sus 5 lay.nki"
                                   #p"/Brass/6 French Horns/1 Long/F 6FH Sus Accent.nki"
                                   #p"/Brass/6 French Horns/1 Long/F 6FH Sus Adventure.nki"
                                   #p"/Brass/6 French Horns/1 Long/F 6FH Sus Bright.nki"
                                   #p"/Brass/6 French Horns/1 Long/F 6FH Sus Forte Piano.nki"
                                   #p"/Brass/6 French Horns/1 Long/F 6FH Sus Mellow.nki"
                                   #p"/Brass/6 French Horns/2 Short/F 6FH 1sec Marc.nki"
                                   #p"/Brass/6 French Horns/2 Short/F 6FH Repetitions.nki"
                                   #p"/Brass/6 French Horns/2 Short/F 6FH Stac Long RR x3.nki"
                                   #p"/Brass/6 French Horns/2 Short/F 6FH Stac Long.nki"
                                   #p"/Brass/6 French Horns/2 Short/F 6FH Stac Short RR x3.nki"
                                   #p"/Brass/6 French Horns/2 Short/F 6FH Stac Short.nki"
                                   #p"/Brass/6 French Horns/3 Effects/F 6FH 1sec Cres.nki"
                                   #p"/Brass/6 French Horns/3 Effects/F 6FH 2sec Cres.nki"
                                   #p"/Brass/6 French Horns/3 Effects/F 6FH 3sec Cres Fltr.nki"
                                   #p"/Brass/6 French Horns/3 Effects/F 6FH Bend Dn HT.nki"
                                   #p"/Brass/6 French Horns/3 Effects/F 6FH Clstr Bend WT.nki"
                                   #p"/Brass/6 French Horns/3 Effects/F 6FH Clstr Gliss Up.nki"
                                   #p"/Brass/6 French Horns/3 Effects/F 6FH Clstr.nki"
                                   #p"/Brass/6 French Horns/3 Effects/F 6FH Flutter Cres Fst.nki"
                                   #p"/Brass/6 French Horns/3 Effects/F 6FH FX Hell.nki"
                                   #p"/Brass/6 French Horns/3 Effects/F 6FH Rips L.nki"
                                   #p"/Brass/6 French Horns/3 Effects/F 6FH Rips S.nki"
                                   #p"/Brass/6 French Horns/3 Effects/F 6FH Rips x.nki"
                                   #p"/Brass/6 French Horns/3 Effects/F 6FH Shake.nki"
                                   #p"/Brass/6 French Horns/3 Effects/F 6FH Trill HT.nki"
                                   #p"/Brass/6 French Horns/3 Effects/F 6FH Trill WT.nki"
                                   #p"/Brass/6 French Horns/4 ModXfd/F 6FH Emotn DXF Leg.nki"
                                   #p"/Brass/6 French Horns/4 ModXfd/F 6FH QLeg DXF RR.nki"
                                   #p"/Brass/6 French Horns/4 ModXfd/F 6FH QLeg DXF slud vs.nki"
                                   #p"/Brass/6 French Horns/4 ModXfd/F 6FH QLeg DXF.nki"
                                   #p"/Brass/6 French Horns/4 ModXfd/F 6FH QLeg Power DXF.nki"
                                   #p"/Brass/6 French Horns/4 ModXfd/F 6FH Sus ACC VEL DXF.nki"
                                   #p"/Brass/6 French Horns/4 ModXfd/F 6FH Sus DXF.nki"
                                   #p"/Brass/6 French Horns/4 ModXfd/F 6FH Sus X-Fade.nki"
                                   #p"/Brass/6 French Horns/5 Keysw/F 6FH Keysw FX C0-D#0.nki"
                                   #p"/Brass/6 French Horns/5 Keysw/F 6FH KS Cres C0-D#0.nki"
                                   #p"/Brass/6 French Horns/5 Keysw/F 6FH KS Sus C0-B0.nki"

                                   #p"/Brass/Solo French Horn/1 Long/F SFH QLeg RR.nki"
                                   #p"/Brass/Solo French Horn/1 Long/F SFH QLeg.nki"
                                   #p"/Brass/Solo French Horn/1 Long/F SFH Sfz Crec.nki"
                                   #p"/Brass/Solo French Horn/1 Long/F SFH Sus.nki"
                                   #p"/Brass/Solo French Horn/2 Short/F SFH Marc.nki"
                                   #p"/Brass/Solo French Horn/2 Short/F SFH Stac RR x6.nki"
                                   #p"/Brass/Solo French Horn/2 Short/F SFH Stac RR.nki"
                                   #p"/Brass/Solo French Horn/4 ModXfd/F SFH QLeg DXF RR.nki"
                                   #p"/Brass/Solo French Horn/4 ModXfd/F SFH QLeg DXF.nki"
                                   #p"/Brass/Solo French Horn/4 ModXfd/F SFH Sus Accent Mod.nki"
                                   #p"/Brass/Solo French Horn/4 ModXfd/F SFH Sus Accent.nki"
                                   #p"/Brass/Solo French Horn/4 ModXfd/F SFH Sus DXF ACC.nki"
                                   #p"/Brass/Solo French Horn/4 ModXfd/F SFH Sus DXF.nki"
                                   #p"/Brass/Solo French Horn/5 Keysw/F SFH KS Sus C0-B0.nki"

                                   #p"/Brass/Solo Piccolo Trumpet/1 Long/F PTP Sus RR.nki"
                                   #p"/Brass/Solo Piccolo Trumpet/1 Long/F PTP Sus.nki"
                                   #p"/Brass/Solo Piccolo Trumpet/2 Short/F PTP Marc.nki"
                                   #p"/Brass/Solo Piccolo Trumpet/2 Short/F PTP Stac RR x6.nki"
                                   #p"/Brass/Solo Piccolo Trumpet/2 Short/F PTP Stac RR.nki"
                                   #p"/Brass/Solo Piccolo Trumpet/3 Effects/F PTP Trill HT.nki"
                                   #p"/Brass/Solo Piccolo Trumpet/3 Effects/F PTP Trill WT.nki"
                                   #p"/Brass/Solo Piccolo Trumpet/4 ModXfd/F PTP Sus acc DT Mod.nki"
                                   #p"/Brass/Solo Piccolo Trumpet/4 ModXfd/F PTP Sus DXF Acc Vel.nki"
                                   #p"/Brass/Solo Piccolo Trumpet/4 ModXfd/F PTP Sus DXF RR.nki"
                                   #p"/Brass/Solo Piccolo Trumpet/4 ModXfd/F PTP Sus DXF.nki"
                                   #p"/Brass/Solo Piccolo Trumpet/5 Keysw/F PTP KS Sus C0-B0.nki"

                                   #p"/Brass/Solo Trombone/1 Long/F STB Mute Sus.nki"
                                   #p"/Brass/Solo Trombone/1 Long/F STB Portato.nki"
                                   #p"/Brass/Solo Trombone/1 Long/F STB QLeg RR.nki"
                                   #p"/Brass/Solo Trombone/1 Long/F STB QLeg.nki"
                                   #p"/Brass/Solo Trombone/1 Long/F STB Sus.nki"
                                   #p"/Brass/Solo Trombone/2 Short/F STB Marc F.nki"
                                   #p"/Brass/Solo Trombone/2 Short/F STB Stac RR x3.nki"
                                   #p"/Brass/Solo Trombone/2 Short/F STB Stac.nki"
                                   #p"/Brass/Solo Trombone/3 Effects/F STB bass SFZ CREC.nki"
                                   #p"/Brass/Solo Trombone/4 ModXfd/F STB Mute Sus DXF.nki"
                                   #p"/Brass/Solo Trombone/4 ModXfd/F STB QLeg DXF RR.nki"
                                   #p"/Brass/Solo Trombone/4 ModXfd/F STB QLeg DXF.nki"
                                   #p"/Brass/Solo Trombone/4 ModXfd/F STB Sus Accent Mod.nki"
                                   #p"/Brass/Solo Trombone/4 ModXfd/F STB Sus DXF ACC.nki"
                                   #p"/Brass/Solo Trombone/4 ModXfd/F STB Sus DXF.nki"
                                   #p"/Brass/Solo Trombone/5 Keysw/F STB KS Sus C5-B5.nki"

                                   #p"/Brass/Solo Trumpet 1/1 Long/F STP Exp PPFF.nki"
                                   #p"/Brass/Solo Trumpet 1/1 Long/F STP Exp.nki"
                                   #p"/Brass/Solo Trumpet 1/1 Long/F STP Port.nki"
                                   #p"/Brass/Solo Trumpet 1/1 Long/F STP Sus Vib.nki"
                                   #p"/Brass/Solo Trumpet 1/1 Long/F STP Sus.nki"
                                   #p"/Brass/Solo Trumpet 1/2 Short/F STP Stac RR.nki"
                                   #p"/Brass/Solo Trumpet 1/2 Short/F STP Stac.nki"
                                   #p"/Brass/Solo Trumpet 1/3 Effects/F STP Sfz Crec.nki"
                                   #p"/Brass/Solo Trumpet 1/3 Effects/F STP Slur.nki"
                                   #p"/Brass/Solo Trumpet 1/4 ModXfd/F STP Nv VB DXF ACC Mid.nki"
                                   #p"/Brass/Solo Trumpet 1/4 ModXfd/F STP Nv Vb DXF ACC Sof.nki"
                                   #p"/Brass/Solo Trumpet 1/4 ModXfd/F STP Sus Acc Mod.nki"
                                   #p"/Brass/Solo Trumpet 1/4 ModXfd/F STP SUS DXF ACC.nki"
                                   #p"/Brass/Solo Trumpet 1/4 ModXfd/F STP SUS DXF.nki"
                                   #p"/Brass/Solo Trumpet 1/4 ModXfd/F STP Vib DXF ACC.nki"
                                   #p"/Brass/Solo Trumpet 1/4 ModXfd/F STP Vib DXF.nki"
                                   #p"/Brass/Solo Trumpet 1/5 Keysw/F STP KS Sus C0-B0.nki"

                                   #p"/Brass/Solo Trumpet 2/1 Long/F ST2 Exp Vib.nki"
                                   #p"/Brass/Solo Trumpet 2/1 Long/F ST2 Marc Vib Long.nki"
                                   #p"/Brass/Solo Trumpet 2/1 Long/F ST2 Portato.nki"
                                   #p"/Brass/Solo Trumpet 2/1 Long/F ST2 QLeg NV RR.nki"
                                   #p"/Brass/Solo Trumpet 2/1 Long/F ST2 QLeg NV.nki"
                                   #p"/Brass/Solo Trumpet 2/1 Long/F ST2 QLeg Vib RR.nki"
                                   #p"/Brass/Solo Trumpet 2/1 Long/F ST2 QLeg Vib.nki"
                                   #p"/Brass/Solo Trumpet 2/1 Long/F ST2 Sus NV.nki"
                                   #p"/Brass/Solo Trumpet 2/2 Short/F ST2 Marc.nki"
                                   #p"/Brass/Solo Trumpet 2/2 Short/F ST2 Stac RR x10.nki"
                                   #p"/Brass/Solo Trumpet 2/2 Short/F ST2 Stac RR x5.nki"
                                   #p"/Brass/Solo Trumpet 2/3 Effects/F ST2 8va Sl Up.nki"
                                   #p"/Brass/Solo Trumpet 2/3 Effects/F ST2 Cres 1 Sec.nki"
                                   #p"/Brass/Solo Trumpet 2/3 Effects/F ST2 Cres 2 Sec.nki"
                                   #p"/Brass/Solo Trumpet 2/3 Effects/F ST2 Cres 3 Sec Fltr.nki"
                                   #p"/Brass/Solo Trumpet 2/3 Effects/F ST2 Falls.nki"
                                   #p"/Brass/Solo Trumpet 2/3 Effects/F ST2 Flutter Cres Fst.nki"
                                   #p"/Brass/Solo Trumpet 2/3 Effects/F ST2 Rips.nki"
                                   #p"/Brass/Solo Trumpet 2/3 Effects/F Stu sfz.nki"
                                   #p"/Brass/Solo Trumpet 2/4 ModXfd/F ST2 QLeg NV DXF RR.nki"
                                   #p"/Brass/Solo Trumpet 2/4 ModXfd/F ST2 QLeg NV DXF.nki"
                                   #p"/Brass/Solo Trumpet 2/4 ModXfd/F ST2 Sus Acc Mod.nki"
                                   #p"/Brass/Solo Trumpet 2/4 ModXfd/F ST2 Sus DXF Acc Vel.nki"
                                   #p"/Brass/Solo Trumpet 2/4 ModXfd/F ST2 Sus NV DXF.nki"
                                   #p"/Brass/Solo Trumpet 2/5 Keysw/F ST2 KS Sus C0-B0.nki"

                                   #p"/Brass/Solo Tuba/1 Long/F STU Exp.nki"
                                   #p"/Brass/Solo Tuba/1 Long/F STU Mute Sus.nki"
                                   #p"/Brass/Solo Tuba/1 Long/F Stu sfz.nki"
                                   #p"/Brass/Solo Tuba/1 Long/F STU Sus.nki"
                                   #p"/Brass/Solo Tuba/2 Short/F STU Marc.nki"
                                   #p"/Brass/Solo Tuba/2 Short/F STU Stac RR x3.nki"
                                   #p"/Brass/Solo Tuba/2 Short/F STU Stac.nki"
                                   #p"/Brass/Solo Tuba/4 ModXfd/F STU Sus Accent Mod.nki"
                                   #p"/Brass/Solo Tuba/4 ModXfd/F STU Sus DXF Acc Vel.nki"
                                   #p"/Brass/Solo Tuba/4 ModXfd/F STU Sus DXF.nki"
                                   #p"/Brass/Solo Tuba/5 Keysw/F STU KS Sus C4-B4.nki"

                                   #p"/Percussion/CymGong/F 12 Band Cymbal.nki"
                                   #p"/Percussion/CymGong/F 12 Cymbal.nki"
                                   #p"/Percussion/CymGong/F 16 German cymbal.nki"
                                   #p"/Percussion/CymGong/F 18 Cymbal.nki"
                                   #p"/Percussion/CymGong/F 18 German Cymbal.nki"
                                   #p"/Percussion/CymGong/F 18 Viennese Cymbal.nki"
                                   #p"/Percussion/CymGong/F 18 Zildjan Roll DXF MOD.nki"
                                   #p"/Percussion/CymGong/F 19 French Cymbal.nki"
                                   #p"/Percussion/CymGong/F 20 Cymbal.nki"
                                   #p"/Percussion/CymGong/F 20 French Cymbal.nki"
                                   #p"/Percussion/CymGong/F 21 French Cymbal.nki"
                                   #p"/Percussion/CymGong/F 22 Cymbal.nki"
                                   #p"/Percussion/CymGong/F 23 Gong.nki"
                                   #p"/Percussion/CymGong/F 26 Zildjan Crash.nki"
                                   #p"/Percussion/CymGong/F 26 Zildjan Roll DXF MOD.nki"
                                   #p"/Percussion/CymGong/F 28 Gong.nki"
                                   #p"/Percussion/CymGong/F 37 Chinese Tam Tam.nki"
                                   #p"/Percussion/CymGong/F 48 Gong.nki"
                                   #p"/Percussion/CymGong/F 60 Gong 2.nki"
                                   #p"/Percussion/CymGong/F 60 Gong.nki"
                                   #p"/Percussion/CymGong/F All Cymbals.nki"
                                   #p"/Percussion/CymGong/F All Gongs.nki"
                                   #p"/Percussion/Drums/F 3 Snares DXF Rolls.nki"
                                   #p"/Percussion/Drums/F 3 Snares.nki"
                                   #p"/Percussion/Drums/F 5 Concert Toms.nki"
                                   #p"/Percussion/Drums/F Bass Drum Concert.nki"
                                   #p"/Percussion/Drums/F Bass Drum Wagner.nki"
                                   #p"/Percussion/Drums/F Field Ens.nki"
                                   #p"/Percussion/Drums/F Field Funeral Tenor.nki"
                                   #p"/Percussion/Drums/F Mahler Hammer.nki"
                                   #p"/Percussion/Drums/F Roto Toms RR.nki"
                                   #p"/Percussion/Drums/F Snare Ens Large.nki"
                                   #p"/Percussion/Drums/F Snare Ens Small.nki"
                                   #p"/Percussion/Drums/F Taiko Drums.nki"
                                   #p"/Percussion/Drums/F Timp Crec L.nki"
                                   #p"/Percussion/Drums/F Timp Crec S.nki"
                                   #p"/Percussion/Drums/F Timp Hits LR.nki"
                                   #p"/Percussion/Drums/F Timp Roll DXF Mod Hits.nki"
                                   #p"/Percussion/Drums/F Timp Roll DXF Mod.nki"
                                   #p"/Percussion/Drums/F Timp Sft Mlt Hits LR.nki"
                                   #p"/Percussion/Drums/S Bass Drum Wagner.nki"
                                   #p"/Percussion/Metals/F All Anvils.nki"
                                   #p"/Percussion/Metals/F Anvil Low.nki"
                                   #p"/Percussion/Metals/F Anvil.nki"
                                   #p"/Percussion/Metals/F Artillery Shells.nki"
                                   #p"/Percussion/Metals/F Bowed Crotales.nki"
                                   #p"/Percussion/Metals/F Celesta.nki"
                                   #p"/Percussion/Metals/F Crotales.nki"
                                   #p"/Percussion/Metals/F Glock Mellow.nki"
                                   #p"/Percussion/Metals/F Glock.nki"
                                   #p"/Percussion/Metals/F Hall Noise.nki"
                                   #p"/Percussion/Metals/F Huge Anvils.nki"
                                   #p"/Percussion/Metals/F Orch chimes.nki"
                                   #p"/Percussion/Metals/F Sleigh Bells RR.nki"
                                   #p"/Percussion/Metals/F Steel Plates.nki"
                                   #p"/Percussion/Metals/F Triangle 2.nki"
                                   #p"/Percussion/Metals/F Triangle.nki"
                                   #p"/Percussion/Metals/F Various Metals.nki"
                                   #p"/Percussion/Metals/F Vibes.nki"
                                   #p"/Percussion/Metals/F Waterphone.nki"
                                   #p"/Percussion/Wood/F All Sticks.nki"
                                   #p"/Percussion/Wood/F Castanets.nki"
                                   #p"/Percussion/Wood/F Guiro RR.nki"
                                   #p"/Percussion/Wood/F Marimba.nki"
                                   #p"/Percussion/Wood/F Puilli Sticks.nki"
                                   #p"/Percussion/Wood/F Slap Sticks.nki"
                                   #p"/Percussion/Wood/F Steinway B.nki"
                                   #p"/Percussion/Wood/F Tambourine 2.nki"
                                   #p"/Percussion/Wood/F Tambourine.nki"
                                   #p"/Percussion/Wood/F Tiny Puilli Sticks.nki"
                                   #p"/Percussion/Wood/F Various Perc.nki"
                                   #p"/Percussion/Wood/F Washboard RR.nki"
                                   #p"/Percussion/Wood/F Wind Machine.nki"
                                   #p"/Percussion/Wood/F Woodblock symphony.nki"
                                   #p"/Percussion/Wood/F Xylophone.nki"


                                   #p"/Strings/10 Cellos/1 Long/F VCS Butter Leg Forte.nki"
                                   #p"/Strings/10 Cellos/1 Long/F VCS Butter Legato.nki"
                                   #p"/Strings/10 Cellos/1 Long/F VCS Exp Vib FST.nki"
                                   #p"/Strings/10 Cellos/1 Long/F VCS Exp Vib.nki"
                                   #p"/Strings/10 Cellos/1 Long/F VCS Flowing.nki"
                                   #p"/Strings/10 Cellos/1 Long/F VCS Lyr Fast.nki"
                                   #p"/Strings/10 Cellos/1 Long/F VCS Lyr.nki"
                                   #p"/Strings/10 Cellos/1 Long/F VCS Non Vib.nki"
                                   #p"/Strings/10 Cellos/1 Long/F VCS Port Shrt.nki"
                                   #p"/Strings/10 Cellos/1 Long/F VCS Port.nki"
                                   #p"/Strings/10 Cellos/1 Long/F VCS QLeg Sord.nki"
                                   #p"/Strings/10 Cellos/1 Long/F VCS QLeg.nki"
                                   #p"/Strings/10 Cellos/1 Long/F VCS Run Simulator.nki"
                                   #p"/Strings/10 Cellos/1 Long/F VCS Sord leg dim.nki"
                                   #p"/Strings/10 Cellos/1 Long/F VCS Sus Vib Hard.nki"
                                   #p"/Strings/10 Cellos/1 Long/F VCS Sus Vib Soft Leg.nki"
                                   #p"/Strings/10 Cellos/1 Long/F VCS Sus Vib Soft.nki"
                                   #p"/Strings/10 Cellos/1 Long/F VCS Sus Vib.nki"
                                   #p"/Strings/10 Cellos/1 Long/F VCS Trem Leg.nki"
                                   #p"/Strings/10 Cellos/1 Long/F VCS Trem.nki"
                                   #p"/Strings/10 Cellos/2 Short/C VCS Quick Up Dn.nki"
                                   #p"/Strings/10 Cellos/2 Short/F VCS Bartok Pizz RR x3.nki"
                                   #p"/Strings/10 Cellos/2 Short/F VCS Bartok Pizz.nki"
                                   #p"/Strings/10 Cellos/2 Short/F VCS Col Legno RR x3.nki"
                                   #p"/Strings/10 Cellos/2 Short/F VCS Col Legno.nki"
                                   #p"/Strings/10 Cellos/2 Short/F VCS Marc Mod Col RR x6.nki"
                                   #p"/Strings/10 Cellos/2 Short/F VCS Marc RR x6.nki"
                                   #p"/Strings/10 Cellos/2 Short/F VCS Marc RR.nki"
                                   #p"/Strings/10 Cellos/2 Short/F VCS Mart Up DN.nki"
                                   #p"/Strings/10 Cellos/2 Short/F VCS Pizz NEW.nki"
                                   #p"/Strings/10 Cellos/2 Short/F VCS Pizz RR x3.nki"
                                   #p"/Strings/10 Cellos/2 Short/F VCS Pizz vs Bart RR x3.nki"
                                   #p"/Strings/10 Cellos/2 Short/F VCS Pizz.nki"
                                   #p"/Strings/10 Cellos/2 Short/F VCS Quick Up DN x6.nki"
                                   #p"/Strings/10 Cellos/2 Short/F VCS Quick Up DN.nki"
                                   #p"/Strings/10 Cellos/2 Short/F VCS Spiccato RR x6.nki"
                                   #p"/Strings/10 Cellos/2 Short/F VCS Spiccato RR.nki"
                                   #p"/Strings/10 Cellos/3 Effects/F VCS Crec.nki"
                                   #p"/Strings/10 Cellos/3 Effects/F VCS FX.nki"
                                   #p"/Strings/10 Cellos/3 Effects/F VCS Sul Pont Trem DXF.nki"
                                   #p"/Strings/10 Cellos/3 Effects/F VCS Sul Pont.nki"
                                   #p"/Strings/10 Cellos/3 Effects/F VCS Trill H.nki"
                                   #p"/Strings/10 Cellos/3 Effects/F VCS Trill W.nki"
                                   #p"/Strings/10 Cellos/4 ModXfd/F VCS DXF Sus Acc Vel.nki"
                                   #p"/Strings/10 Cellos/4 ModXfd/F VCS DXF Sus Vib Slow.nki"
                                   #p"/Strings/10 Cellos/4 ModXfd/F VCS DXF Sus Vib.nki"
                                   #p"/Strings/10 Cellos/4 ModXfd/F VCS Emotn DXF 1.nki"
                                   #p"/Strings/10 Cellos/4 ModXfd/F VCS Emotn DXF 2.nki"
                                   #p"/Strings/10 Cellos/4 ModXfd/F VCS Emotn DXF 3.nki"
                                   #p"/Strings/10 Cellos/4 ModXfd/F VCS Emotn DXF 4.nki"
                                   #p"/Strings/10 Cellos/4 ModXfd/F VCS Exp Vib DXF.nki"
                                   #p"/Strings/10 Cellos/4 ModXfd/F VCS Fast Acc Mod.nki"
                                   #p"/Strings/10 Cellos/4 ModXfd/F VCS Non Vib-Sus XFD.nki"
                                   #p"/Strings/10 Cellos/4 ModXfd/F VCS QLeg DXF sl up.nki"
                                   #p"/Strings/10 Cellos/4 ModXfd/F VCS QLeg DXF.nki"
                                   #p"/Strings/10 Cellos/4 ModXfd/F VCS QLeg Sord DXF.nki"
                                   #p"/Strings/10 Cellos/4 ModXfd/F VCS Soft Vib XFD Trem.nki"
                                   #p"/Strings/10 Cellos/4 ModXfd/F VCS sus accent mod.nki"
                                   #p"/Strings/10 Cellos/5 Keysw/F VCS KS Shrt RR C0-F#0.nki"
                                   #p"/Strings/10 Cellos/5 Keysw/F VCS KS Sus C0-B0.nki"

                                   #p"/Strings/10 Violas/1 Long/F VAS Butter Leg.nki"
                                   #p"/Strings/10 Violas/1 Long/F VAS Exp Fst.nki"
                                   #p"/Strings/10 Violas/1 Long/F VAS Exp slow.nki"
                                   #p"/Strings/10 Violas/1 Long/F VAS QLeg Flaut.nki"
                                   #p"/Strings/10 Violas/1 Long/F VAS QLeg Sord.nki"
                                   #p"/Strings/10 Violas/1 Long/F VAS QLeg.nki"
                                   #p"/Strings/10 Violas/1 Long/F VAS Sus 2.nki"
                                   #p"/Strings/10 Violas/1 Long/F VAS Sus Soft Leg.nki"
                                   #p"/Strings/10 Violas/1 Long/F VAS Sus Soft.nki"
                                   #p"/Strings/10 Violas/1 Long/F VAS Sus.nki"
                                   #p"/Strings/10 Violas/2 Short/C VAS Shrt Mart Up Dn.nki"
                                   #p"/Strings/10 Violas/2 Short/F VAS Bartok Pizz RR x3.nki"
                                   #p"/Strings/10 Violas/2 Short/F VAS Bartok Pizz.nki"
                                   #p"/Strings/10 Violas/2 Short/F VAS Col Legno RR x3.nki"
                                   #p"/Strings/10 Violas/2 Short/F VAS Col Legno.nki"
                                   #p"/Strings/10 Violas/2 Short/F VAS Marc Long.nki"
                                   #p"/Strings/10 Violas/2 Short/F VAS Marc Shrt.nki"
                                   #p"/Strings/10 Violas/2 Short/F VAS MArt Up Dn Marc.nki"
                                   #p"/Strings/10 Violas/2 Short/F VAS Mart Up Dn.nki"
                                   #p"/Strings/10 Violas/2 Short/F VAS Pizz RR x3.nki"
                                   #p"/Strings/10 Violas/2 Short/F VAS Pizz vs Bart RR x3.nki"
                                   #p"/Strings/10 Violas/2 Short/F VAS Pizz.nki"
                                   #p"/Strings/10 Violas/2 Short/F VAS Repetitions.nki"
                                   #p"/Strings/10 Violas/2 Short/F VAS S Mart UD Marc S x6.nki"
                                   #p"/Strings/10 Violas/2 Short/F VAS S Mart UD Marc S.nki"
                                   #p"/Strings/10 Violas/2 Short/F VAS Shrt Mart Up Dn.nki"
                                   #p"/Strings/10 Violas/2 Short/F VAS Stac MOD Col RR.nki"
                                   #p"/Strings/10 Violas/2 Short/F VAS Stac RR x4.nki"
                                   #p"/Strings/10 Violas/2 Short/F VAS Stac RR x8.nki"
                                   #p"/Strings/10 Violas/3 Effects/F VAS SulPont.nki"
                                   #p"/Strings/10 Violas/3 Effects/F VAS Trem.nki"
                                   #p"/Strings/10 Violas/3 Effects/F VAS Trill HT.nki"
                                   #p"/Strings/10 Violas/3 Effects/F VAS Trill WT.nki"
                                   #p"/Strings/10 Violas/4 ModXfd/F VAS DXF Sus Acc Vel.nki"
                                   #p"/Strings/10 Violas/4 ModXfd/F VAS Emotn DXF 1.nki"
                                   #p"/Strings/10 Violas/4 ModXfd/F VAS Emotn DXF Acc Vl.nki"
                                   #p"/Strings/10 Violas/4 ModXfd/F VAS Exp Fst DXF.nki"
                                   #p"/Strings/10 Violas/4 ModXfd/F VAS Exp slow DXF.nki"
                                   #p"/Strings/10 Violas/4 ModXfd/F VAS leg Exp acc MOD.nki"
                                   #p"/Strings/10 Violas/4 ModXfd/F VAS QLeg DXF sl up.nki"
                                   #p"/Strings/10 Violas/4 ModXfd/F VAS QLeg DXF.nki"
                                   #p"/Strings/10 Violas/4 ModXfd/F VAS QLeg Sord DXF.nki"
                                   #p"/Strings/10 Violas/4 ModXfd/F VAS Sul Pont Trem DXF.nki"
                                   #p"/Strings/10 Violas/4 ModXfd/F VAS sus accent mod.nki"
                                   #p"/Strings/10 Violas/4 ModXfd/F VAS Sus NV VIB X-FADE.nki"
                                   #p"/Strings/10 Violas/5 Keysw/F VAS KS Shrt RR C0-F#0.nki"
                                   #p"/Strings/10 Violas/5 Keysw/F VAS KS Sus C0-B0.nki"

                                   #p"/Strings/11 Violins/1 Long/F 11V Butter Leg Forte.nki"
                                   #p"/Strings/11 Violins/1 Long/F 11V Butter Legato.nki"
                                   #p"/Strings/11 Violins/1 Long/F 11V Exp Dim.nki"
                                   #p"/Strings/11 Violins/1 Long/F 11V Exp.nki"
                                   #p"/Strings/11 Violins/1 Long/F 11V Grand Detache.nki"
                                   #p"/Strings/11 Violins/1 Long/F 11V Harmonics.nki"
                                   #p"/Strings/11 Violins/1 Long/F 11V Lyr A.nki"
                                   #p"/Strings/11 Violins/1 Long/F 11V Lyr B.nki"
                                   #p"/Strings/11 Violins/1 Long/F 11V QLeg Flaut.nki"
                                   #p"/Strings/11 Violins/1 Long/F 11V QLeg Sord.nki"
                                   #p"/Strings/11 Violins/1 Long/F 11V QLeg.nki"
                                   #p"/Strings/11 Violins/1 Long/F 11V Run Simulator.nki"
                                   #p"/Strings/11 Violins/1 Long/F 11V Sus Vib Hard.nki"
                                   #p"/Strings/11 Violins/1 Long/F 11V Sus Vib Soft Leg.nki"
                                   #p"/Strings/11 Violins/1 Long/F 11V Sus Vib Soft.nki"
                                   #p"/Strings/11 Violins/1 Long/F 11V Sus Vib.nki"
                                   #p"/Strings/11 Violins/2 Short/C 11V Quick Up Dn.nki"
                                   #p"/Strings/11 Violins/2 Short/F 11V Col Legno RR x3.nki"
                                   #p"/Strings/11 Violins/2 Short/F 11V Col Legno.nki"
                                   #p"/Strings/11 Violins/2 Short/F 11V Marc Short.nki"
                                   #p"/Strings/11 Violins/2 Short/F 11V Marc.nki"
                                   #p"/Strings/11 Violins/2 Short/F 11V Mart Up Dn Marc.nki"
                                   #p"/Strings/11 Violins/2 Short/F 11V Mart Up Dn Spic.nki"
                                   #p"/Strings/11 Violins/2 Short/F 11V Mart Up Dn.nki"
                                   #p"/Strings/11 Violins/2 Short/F 11V Med Shrt 3-Way RR.nki"
                                   #p"/Strings/11 Violins/2 Short/F 11V Quick Up Dn Marc x6.nki"
                                   #p"/Strings/11 Violins/2 Short/F 11V Quick Up Dn Marc.nki"
                                   #p"/Strings/11 Violins/2 Short/F 11V Quick Up Dn Spic.nki"
                                   #p"/Strings/11 Violins/2 Short/F 11V Quick Up Dn.nki"
                                   #p"/Strings/11 Violins/2 Short/F 11V Repetitions.nki"
                                   #p"/Strings/11 Violins/2 Short/F 11V Short 3-Way RR.nki"
                                   #p"/Strings/11 Violins/2 Short/F 11V Shrt Spic 3Wy RR.nki"
                                   #p"/Strings/11 Violins/2 Short/F 11V Spic.nki"
                                   #p"/Strings/11 Violins/2 Short/F 11V Spiccato 2 RR x6.nki"
                                   #p"/Strings/11 Violins/2 Short/F 11V Spiccato 2 RR.nki"
                                   #p"/Strings/11 Violins/2 Short/F 11V Stac Mod Col RR x2.nki"
                                   #p"/Strings/11 Violins/2 Short/F 11V Stac RR x2.nki"
                                   #p"/Strings/11 Violins/3 Effects/F 11 Violins Scratching FX.nki"
                                   #p"/Strings/11 Violins/3 Effects/F 11V 5th Slide DN Hrd.nki"
                                   #p"/Strings/11 Violins/3 Effects/F 11V 5th Slide up Hrd.nki"
                                   #p"/Strings/11 Violins/3 Effects/F 11V Gl L.nki"
                                   #p"/Strings/11 Violins/3 Effects/F 11V Gl S.nki"
                                   #p"/Strings/11 Violins/3 Effects/F 11V Psycho Rip.nki"
                                   #p"/Strings/11 Violins/3 Effects/F 11V Run Dn Psycho.nki"
                                   #p"/Strings/11 Violins/3 Effects/F 11V Run Up Psycho 2.nki"
                                   #p"/Strings/11 Violins/3 Effects/F 11V Run Up Psycho RR.nki"
                                   #p"/Strings/11 Violins/3 Effects/F 11V SFX Clusters.nki"
                                   #p"/Strings/11 Violins/3 Effects/F 11V Slw Trll FX.nki"
                                   #p"/Strings/11 Violins/3 Effects/F 11V Sul Pont.nki"
                                   #p"/Strings/11 Violins/3 Effects/F 11V Tremolo F.nki"
                                   #p"/Strings/11 Violins/3 Effects/F 11v Trill h.nki"
                                   #p"/Strings/11 Violins/3 Effects/F 11v Trill W.nki"
                                   #p"/Strings/11 Violins/4 ModXfd/F 11V Accent sus mod.nki"
                                   #p"/Strings/11 Violins/4 ModXfd/F 11V DXF EXP Fast.nki"
                                   #p"/Strings/11 Violins/4 ModXfd/F 11V DXF EXP Slow.nki"
                                   #p"/Strings/11 Violins/4 ModXfd/F 11V DXF Sus Vib Ac Vl.nki"
                                   #p"/Strings/11 Violins/4 ModXfd/F 11v Emotn DXF 1.nki"
                                   #p"/Strings/11 Violins/4 ModXfd/F 11v Emotn DXF 2.nki"
                                   #p"/Strings/11 Violins/4 ModXfd/F 11V Flaut Harm DXF.nki"
                                   #p"/Strings/11 Violins/4 ModXfd/F 11V QLeg DXF slud vs.nki"
                                   #p"/Strings/11 Violins/4 ModXfd/F 11V QLeg DXF.nki"
                                   #p"/Strings/11 Violins/4 ModXfd/F 11V QLeg Sord DXF.nki"
                                   #p"/Strings/11 Violins/4 ModXfd/F 11V Sul Pont Trem DXF.nki"
                                   #p"/Strings/11 Violins/4 ModXfd/F 11V Sus NV Vib X-Fade.nki"
                                   #p"/Strings/11 Violins/4 ModXfd/F 11V Sus Vib DXF Slow.nki"
                                   #p"/Strings/11 Violins/4 ModXfd/F 11V Sus Vib DXF.nki"
                                   #p"/Strings/11 Violins/5 Keysw/F 11V KS Shrt RR C0-F#0.nki"
                                   #p"/Strings/11 Violins/5 Keysw/F 11V KS Sus C0-B0.nki"

                                   #p"/Strings/18 Violins/1 Long/F 18V Butter Leg Forte.nki"
                                   #p"/Strings/18 Violins/1 Long/F 18V Butter Legato.nki"
                                   #p"/Strings/18 Violins/1 Long/F 18V Exp Fast.nki"
                                   #p"/Strings/18 Violins/1 Long/F 18V Exp.nki"
                                   #p"/Strings/18 Violins/1 Long/F 18V Lyr Fast.nki"
                                   #p"/Strings/18 Violins/1 Long/F 18V Lyr.nki"
                                   #p"/Strings/18 Violins/1 Long/F 18V Non Vib Fast.nki"
                                   #p"/Strings/18 Violins/1 Long/F 18v Non VIb-Sus XF.nki"
                                   #p"/Strings/18 Violins/1 Long/F 18V Non Vib.nki"
                                   #p"/Strings/18 Violins/1 Long/F 18v NonVib-EXPFST XF.nki"
                                   #p"/Strings/18 Violins/1 Long/F 18V QLeg.nki"
                                   #p"/Strings/18 Violins/1 Long/F 18V Sord Slow.nki"
                                   #p"/Strings/18 Violins/1 Long/F 18V Sord.nki"
                                   #p"/Strings/18 Violins/1 Long/F 18V Sus Vib Hard.nki"
                                   #p"/Strings/18 Violins/1 Long/F 18V Sus Vib Soft Leg.nki"
                                   #p"/Strings/18 Violins/1 Long/F 18V Sus Vib Soft.nki"
                                   #p"/Strings/18 Violins/1 Long/F 18V Sus Vib.nki"
                                   #p"/Strings/18 Violins/1 Long/F 18V Trem LeG.nki"
                                   #p"/Strings/18 Violins/2 Short/C 18V Quick Up Dn.nki"
                                   #p"/Strings/18 Violins/2 Short/F 18V Bartok Pizz RR.nki"
                                   #p"/Strings/18 Violins/2 Short/F 18V Bartok Pizz.nki"
                                   #p"/Strings/18 Violins/2 Short/F 18V Marc Long.nki"
                                   #p"/Strings/18 Violins/2 Short/F 18V Marc Med Short.nki"
                                   #p"/Strings/18 Violins/2 Short/F 18V Marc Short.nki"
                                   #p"/Strings/18 Violins/2 Short/F 18V Mart Ud Marc Med.nki"
                                   #p"/Strings/18 Violins/2 Short/F 18V Mart ud marc shrt.nki"
                                   #p"/Strings/18 Violins/2 Short/F 18V Mart Up Dn.nki"
                                   #p"/Strings/18 Violins/2 Short/F 18V Pizz RR x3.nki"
                                   #p"/Strings/18 Violins/2 Short/F 18V Pizz vs Bart RR x3.nki"
                                   #p"/Strings/18 Violins/2 Short/F 18V Pizz.nki"
                                   #p"/Strings/18 Violins/2 Short/F 18V Quick UD Marc S x6.nki"
                                   #p"/Strings/18 Violins/2 Short/F 18V Quick UD Marc S.nki"
                                   #p"/Strings/18 Violins/2 Short/F 18V Quick UD Marc UD.nki"
                                   #p"/Strings/18 Violins/2 Short/F 18V Quick Up Dn.nki"
                                   #p"/Strings/18 Violins/2 Short/F 18v Short 3-Way RR.nki"
                                   #p"/Strings/18 Violins/2 Short/F 18V Spiccato RR x4.nki"
                                   #p"/Strings/18 Violins/2 Short/F 18V Spiccato RR.nki"
                                   #p"/Strings/18 Violins/3 Effects/F 18V Clstr & Air.nki"
                                   #p"/Strings/18 Violins/3 Effects/F 18V Pendereki.nki"
                                   #p"/Strings/18 Violins/3 Effects/F 18V Slr faST.nki"
                                   #p"/Strings/18 Violins/3 Effects/F 18V Slr mED.nki"
                                   #p"/Strings/18 Violins/3 Effects/F 18V Slr sLOW.nki"
                                   #p"/Strings/18 Violins/3 Effects/F 18V Slr xFaST.nki"
                                   #p"/Strings/18 Violins/4 ModXfd/F 18V accent sus mod.nki"
                                   #p"/Strings/18 Violins/4 ModXfd/F 18v Emotn DXF 1.nki"
                                   #p"/Strings/18 Violins/4 ModXfd/F 18v Emotn DXF 2.nki"
                                   #p"/Strings/18 Violins/4 ModXfd/F 18V Emotn DXF Acc V1.nki"
                                   #p"/Strings/18 Violins/4 ModXfd/F 18V Exp Fast DXF.nki"
                                   #p"/Strings/18 Violins/4 ModXfd/F 18V Exp LEG ACC DXF.nki"
                                   #p"/Strings/18 Violins/4 ModXfd/F 18V Exp LEG ACC MOD.nki"
                                   #p"/Strings/18 Violins/4 ModXfd/F 18V QLeg DXF slud vs.nki"
                                   #p"/Strings/18 Violins/4 ModXfd/F 18V QLeg DXF slup vs.nki"
                                   #p"/Strings/18 Violins/4 ModXfd/F 18V QLeg DXF.nki"
                                   #p"/Strings/18 Violins/4 ModXfd/F 18V Sord Emotn DXF Vl.nki"
                                   #p"/Strings/18 Violins/4 ModXfd/F 18V Sord Mod XFD Dyn.nki"
                                   #p"/Strings/18 Violins/4 ModXfd/F 18V Sus Vib DXF LegVL.nki"
                                   #p"/Strings/18 Violins/4 ModXfd/F 18V Sus Vib DXF Slow.nki"
                                   #p"/Strings/18 Violins/4 ModXfd/F 18V Sus Vib DXF SLR2VL.nki"
                                   #p"/Strings/18 Violins/4 ModXfd/F 18V Sus Vib DXF SLRVL.nki"
                                   #p"/Strings/18 Violins/4 ModXfd/F 18V Sus Vib DXF.nki"
                                   #p"/Strings/18 Violins/4 ModXfd/F 18V Sus-Vib Xf TREM.nki"
                                   #p"/Strings/18 Violins/5 Keysw/F 18V KS Shrt RR C0-F#0.nki"
                                   #p"/Strings/18 Violins/5 Keysw/F 18V KS Sus C0-B0.nki"

                                   #p"/Strings/3 Cellos/1 Long/F 3VC Sus Vib.nki"
                                   #p"/Strings/3 Cellos/4 ModXfd/F 3VC Sus Vib DXF.nki"
                                   #p"/Strings/4 Violins/1 Long/F 4VL Sus Vib.nki"
                                   #p"/Strings/4 Violins/4 ModXfd/F 4VL Sus Vib DXF.nki"

                                   #p"/Strings/9 Double Basses/1 Long/F CBS Big Sus.nki"
                                   #p"/Strings/9 Double Basses/1 Long/F Cbs Exp 2x Crec.nki"
                                   #p"/Strings/9 Double Basses/1 Long/F Cbs Exp fast.nki"
                                   #p"/Strings/9 Double Basses/1 Long/F Cbs Exp.nki"
                                   #p"/Strings/9 Double Basses/1 Long/F Cbs Forte Piano.nki"
                                   #p"/Strings/9 Double Basses/1 Long/F Cbs Port.nki"
                                   #p"/Strings/9 Double Basses/1 Long/F CBS Sforzando.nki"
                                   #p"/Strings/9 Double Basses/1 Long/F Cbs Sus Vib Hard.nki"
                                   #p"/Strings/9 Double Basses/1 Long/F Cbs Sus Vib Soft Leg.nki"
                                   #p"/Strings/9 Double Basses/1 Long/F Cbs Sus Vib Soft.nki"
                                   #p"/Strings/9 Double Basses/1 Long/F Cbs Sus Vib.nki"
                                   #p"/Strings/9 Double Basses/1 Long/F Cbs Trem Leg.nki"
                                   #p"/Strings/9 Double Basses/1 Long/F Cbs Trem.nki"
                                   #p"/Strings/9 Double Basses/2 Short/C CBS Quick UD mod slap.nki"
                                   #p"/Strings/9 Double Basses/2 Short/C CBS Quick Up Dn.nki"
                                   #p"/Strings/9 Double Basses/2 Short/F CBS Mart Up Dn.nki"
                                   #p"/Strings/9 Double Basses/2 Short/F CBS Pizz mod slaps.nki"
                                   #p"/Strings/9 Double Basses/2 Short/F CBS Pizz.nki"
                                   #p"/Strings/9 Double Basses/2 Short/F CBS Quick UD Mod Slap.nki"
                                   #p"/Strings/9 Double Basses/2 Short/F CBS Quick Up Dn x6.nki"
                                   #p"/Strings/9 Double Basses/2 Short/F CBS Quick Up Dn.nki"
                                   #p"/Strings/9 Double Basses/2 Short/F Cbs Slaps.nki"
                                   #p"/Strings/9 Double Basses/3 Effects/F Cbs Crec.nki"
                                   #p"/Strings/9 Double Basses/3 Effects/F Cbs FX.nki"
                                   #p"/Strings/9 Double Basses/4 ModXfd/F Cbs DXF EXP Acc Vel.nki"
                                   #p"/Strings/9 Double Basses/4 ModXfd/F Cbs DXF Sus Slow.nki"
                                   #p"/Strings/9 Double Basses/4 ModXfd/F Cbs DXF Sus.nki"
                                   #p"/Strings/9 Double Basses/4 ModXfd/F Cbs Emotn DXF 1.nki"
                                   #p"/Strings/9 Double Basses/4 ModXfd/F Cbs Emotn DXF 2.nki"
                                   #p"/Strings/9 Double Basses/4 ModXfd/F Cbs Emotn DXF Acc Vl.nki"
                                   #p"/Strings/9 Double Basses/4 ModXfd/F Cbs EXP Fast DXF.nki"
                                   #p"/Strings/9 Double Basses/4 ModXfd/F Cbs EXP LG DXF ACC VL.nki"
                                   #p"/Strings/9 Double Basses/4 ModXfd/F CBS sus accent mod.nki"
                                   #p"/Strings/9 Double Basses/4 ModXfd/F Cbs Sus Vib X-Fade.nki"
                                   #p"/Strings/9 Double Basses/4 ModXfd/F Cbs Sus Vib Xf Trem.nki"
                                   #p"/Strings/9 Double Basses/5 Keysw/F CBS KS Shrt RR C4-F#4.nki"
                                   #p"/Strings/9 Double Basses/5 Keysw/F CBS KS Sus C4-B4.nki"

                                   #p"/Strings/Harp/1 Long/C Harp Pluck Long.nki"
                                   #p"/Strings/Harp/1 Long/C Harp pluck roll.nki"
                                   #p"/Strings/Harp/1 Long/C Harp Pluck Short.nki"
                                   #p"/Strings/Harp/1 Long/C Harp Pluck.nki"
                                   #p"/Strings/Harp/1 Long/F Harp Harm.nki"
                                   #p"/Strings/Harp/1 Long/F Harp Pluck long.nki"
                                   #p"/Strings/Harp/1 Long/F Harp pluck roll.nki"
                                   #p"/Strings/Harp/1 Long/F Harp Pluck short.nki"
                                   #p"/Strings/Harp/1 Long/F Harp Pluck.nki"
                                   #p"/Strings/Harp/3 Effects/F Harp Gliss 6 Up+Dn.nki"
                                   #p"/Strings/Harp/3 Effects/F Harp Gliss 9 Up+Dn.nki"
                                   #p"/Strings/Harp/3 Effects/F Harp Gliss Maj Up+Dn.nki"
                                   #p"/Strings/Harp/3 Effects/F Harp Gliss WT Up+Dn.nki"
                                   #p"/Strings/Harp/3 Effects/F Harp Psycho Drone C.nki"

                                   #p"/Strings/Harpsichord/1 Long/F Harpsichord.nki"
                                   #p"/Strings/Large String Ens/F 50 Piece Str Sec Fst.nki"
                                   #p"/Strings/Large String Ens/F 50 Piece Str Sec Leg.nki"
                                   #p"/Strings/Large String Ens/F 50 Piece Str Sec Sus.nki"
                                   #p"/Strings/Large String Ens/F 60 PIece Str Sec eXP.nki"
                                   #p"/Strings/Large String Ens/F 60 Piece Str Sec Pizz.nki"
                                   #p"/Strings/Large String Ens/F 60 Piece Str Sec Sus.nki"
                                   #p"/Strings/Large String Ens/F 70 Piece QLeg Slow.nki"
                                   #p"/Strings/Large String Ens/F 70 Piece QLeg Sord.nki"
                                   #p"/Strings/Large String Ens/F 70 Piece QLeg.nki"
                                   #p"/Strings/Large String Ens/F 70 Piece Str Marc RR.nki"
                                   #p"/Strings/Large String Ens/F 70 Piece Str sec eXP.nki"
                                   #p"/Strings/Large String Ens/F 70 Piece Str Sec Pizz.nki"
                                   #p"/Strings/Large String Ens/F 70 Piece Str Sec Sus.nki"
                                   #p"/Strings/Large String Ens/F Chamber Ens Flautando.nki"
                                   #p"/Strings/Large String Ens/F Chamber Ensemble.nki"
                                   #p"/Strings/Large String Ens/F String Quartet QLeg RR.nki"
                                   #p"/Strings/Large String Ens/F String Quartet QLeg.nki"

                                   #p"/Strings/Solo Cello/1 Long/F SVC Double Bow Exp.nki"
                                   #p"/Strings/Solo Cello/1 Long/F SVC Exp Dn.nki"
                                   #p"/Strings/Solo Cello/1 Long/F SVC Exp up.nki"
                                   #p"/Strings/Solo Cello/1 Long/F SVC Exp Vib.nki"
                                   #p"/Strings/Solo Cello/1 Long/F SVC Leg Vib.nki"
                                   #p"/Strings/Solo Cello/1 Long/F SVC Non Vib.nki"
                                   #p"/Strings/Solo Cello/1 Long/F SVC QLeg RR.nki"
                                   #p"/Strings/Solo Cello/1 Long/F SVC QLeg.nki"
                                   #p"/Strings/Solo Cello/1 Long/F SVC Sul Tasto Leg.nki"
                                   #p"/Strings/Solo Cello/1 Long/F SVC Sus Accent.nki"
                                   #p"/Strings/Solo Cello/1 Long/F SVC Sus Vib Hard.nki"
                                   #p"/Strings/Solo Cello/1 Long/F SVC Sus Vib Smooth.nki"
                                   #p"/Strings/Solo Cello/2 Short/F SVC Col Legno RR x3.nki"
                                   #p"/Strings/Solo Cello/2 Short/F SVC Col Legno.nki"
                                   #p"/Strings/Solo Cello/2 Short/F SVC Marc.nki"
                                   #p"/Strings/Solo Cello/2 Short/F SVC Mart Up Dn Marc x6.nki"
                                   #p"/Strings/Solo Cello/2 Short/F SVC Mart Up Dn Marc.nki"
                                   #p"/Strings/Solo Cello/2 Short/F SVC Mart Up Dn.nki"
                                   #p"/Strings/Solo Cello/2 Short/F SVC Pizz RR x3.nki"
                                   #p"/Strings/Solo Cello/2 Short/F SVC Pizz.nki"
                                   #p"/Strings/Solo Cello/3 Effects/F SVC Slur.nki"
                                   #p"/Strings/Solo Cello/4 ModXfd/F SVC NV Vib DXF ACC.nki"
                                   #p"/Strings/Solo Cello/4 ModXfd/F SVC Vib DXF ACC.nki"
                                   #p"/Strings/Solo Cello/5 Keysw/F SVC KS Shrt RR C0-F#0.nki"
                                   #p"/Strings/Solo Cello/5 Keysw/F SVC KS Sus C0-B0.nki"

                                   #p"/Strings/Solo Contrabass/1 Long/F SCB Exp.nki"
                                   #p"/Strings/Solo Contrabass/1 Long/F SCB Lyrical.nki"
                                   #p"/Strings/Solo Contrabass/1 Long/F SCB QLeg Exp.nki"
                                   #p"/Strings/Solo Contrabass/1 Long/F SCB QLeg RR.nki"
                                   #p"/Strings/Solo Contrabass/1 Long/F SCB QLeg.nki"
                                   #p"/Strings/Solo Contrabass/1 Long/F SCB Sus NV.nki"
                                   #p"/Strings/Solo Contrabass/1 Long/F SCB Sus Vib.nki"
                                   #p"/Strings/Solo Contrabass/2 Short/F SCB Col Legno RR x3.nki"
                                   #p"/Strings/Solo Contrabass/2 Short/F SCB Col Legno.nki"
                                   #p"/Strings/Solo Contrabass/2 Short/F SCB Marcato RR x3.nki"
                                   #p"/Strings/Solo Contrabass/2 Short/F SCB Marcato.nki"
                                   #p"/Strings/Solo Contrabass/2 Short/F SCB Martele RR x6.nki"
                                   #p"/Strings/Solo Contrabass/2 Short/F SCB Martele RR.nki"
                                   #p"/Strings/Solo Contrabass/2 Short/F SCB Pizz RR x3.nki"
                                   #p"/Strings/Solo Contrabass/2 Short/F SCB Pizz.nki"
                                   #p"/Strings/Solo Contrabass/2 Short/F SCB Spic Marc RR x6.nki"
                                   #p"/Strings/Solo Contrabass/2 Short/F SCB Spic RR x6.nki"
                                   #p"/Strings/Solo Contrabass/2 Short/F SCB Spic RR.nki"
                                   #p"/Strings/Solo Contrabass/4 ModXfd/F SCB Sus Vib DXF.nki"
                                   #p"/Strings/Solo Contrabass/5 Keysw/F SCB KS Shrt RR C4-F#4.nki"
                                   #p"/Strings/Solo Contrabass/5 Keysw/F SCB KS Sus C4-B4.nki"

                                   #p"/Strings/Solo Viola/1 Long/F SVA Exp 1.nki"
                                   #p"/Strings/Solo Viola/1 Long/F SVA Exp 2.nki"
                                   #p"/Strings/Solo Viola/1 Long/F SVA Exp 3.nki"
                                   #p"/Strings/Solo Viola/1 Long/F SVA Exp Vib Sft.nki"
                                   #p"/Strings/Solo Viola/1 Long/F SVA Non Vib Hard.nki"
                                   #p"/Strings/Solo Viola/1 Long/F SVA Non Vib RR.nki"
                                   #p"/Strings/Solo Viola/1 Long/F SVA QLeg RR.nki"
                                   #p"/Strings/Solo Viola/1 Long/F SVA QLeg.nki"
                                   #p"/Strings/Solo Viola/1 Long/F SVA Sus Vib.nki"
                                   #p"/Strings/Solo Viola/2 Short/F SVA Col Legno RR x3.nki"
                                   #p"/Strings/Solo Viola/2 Short/F SVA Col Legno.nki"
                                   #p"/Strings/Solo Viola/2 Short/F SVA Marc Hard RR x2.nki"
                                   #p"/Strings/Solo Viola/2 Short/F SVA Marc Hard.nki"
                                   #p"/Strings/Solo Viola/2 Short/F SVA Mart RR x4.nki"
                                   #p"/Strings/Solo Viola/2 Short/F SVA Mart RR x8.nki"
                                   #p"/Strings/Solo Viola/2 Short/F SVA Pizz RR x3.nki"
                                   #p"/Strings/Solo Viola/2 Short/F SVA Pizz.nki"
                                   #p"/Strings/Solo Viola/2 Short/F SVA Spic RR x2.nki"
                                   #p"/Strings/Solo Viola/2 Short/F SVA Spic RR x4.nki"
                                   #p"/Strings/Solo Viola/3 Effects/F SVA 8va Slide UP.nki"
                                   #p"/Strings/Solo Viola/3 Effects/F SVA Trill HT.nki"
                                   #p"/Strings/Solo Viola/3 Effects/F SVA Trill WT.nki"
                                   #p"/Strings/Solo Viola/4 ModXfd/F SVA nv vib DXF.nki"
                                   #p"/Strings/Solo Viola/5 Keysw/F SVA KS Shrt RR C0-F#0.nki"
                                   #p"/Strings/Solo Viola/5 Keysw/F SVA KS Sus C0-B0.nki"

                                   #p"/Strings/Solo Violin/1 Long/F SVL Exp 1.nki"
                                   #p"/Strings/Solo Violin/1 Long/F SVL Exp 2.nki"
                                   #p"/Strings/Solo Violin/1 Long/F SVL Exp Crec.nki"
                                   #p"/Strings/Solo Violin/1 Long/F SVL Exp P.nki"
                                   #p"/Strings/Solo Violin/1 Long/F SVL Leg Vib.nki"
                                   #p"/Strings/Solo Violin/1 Long/F SVL Non Vib Hard.nki"
                                   #p"/Strings/Solo Violin/1 Long/F SVL Non Vib Soft.nki"
                                   #p"/Strings/Solo Violin/1 Long/F SVL QLeg Exp P.nki"
                                   #p"/Strings/Solo Violin/1 Long/F SVL QLeg RR.nki"
                                   #p"/Strings/Solo Violin/1 Long/F SVL QLeg.nki"
                                   #p"/Strings/Solo Violin/1 Long/F SVL Sus Vib Hard.nki"
                                   #p"/Strings/Solo Violin/1 Long/F SVL Sus Vib Soft.nki"
                                   #p"/Strings/Solo Violin/2 Short/F SVL Col Legno RR.nki"
                                   #p"/Strings/Solo Violin/2 Short/F SVL Col Legno.nki"
                                   #p"/Strings/Solo Violin/2 Short/F SVL Marc Non Vib Hard.nki"
                                   #p"/Strings/Solo Violin/2 Short/f SVL Marc Vib.nki"
                                   #p"/Strings/Solo Violin/2 Short/F SVL Mart Up Dn x6.nki"
                                   #p"/Strings/Solo Violin/2 Short/F SVL Mart Up Dn.nki"
                                   #p"/Strings/Solo Violin/2 Short/F SVL Pizz RR x3.nki"
                                   #p"/Strings/Solo Violin/2 Short/F SVL Pizz.nki"
                                   #p"/Strings/Solo Violin/2 Short/F SVL Repetitions.nki"
                                   #p"/Strings/Solo Violin/2 Short/F SVL Stac RR x4.nki"
                                   #p"/Strings/Solo Violin/2 Short/F SVL Stac RR.nki"
                                   #p"/Strings/Solo Violin/3 Effects/F SVL 5th Sl UP.nki"
                                   #p"/Strings/Solo Violin/3 Effects/F SVL 8va Sl UP.nki"
                                   #p"/Strings/Solo Violin/3 Effects/F SVL 8vb Sl DN.nki"
                                   #p"/Strings/Solo Violin/3 Effects/F SVL Crec.nki"
                                   #p"/Strings/Solo Violin/3 Effects/F SVL Slur.nki"
                                   #p"/Strings/Solo Violin/3 Effects/F SVL Trill HT.nki"
                                   #p"/Strings/Solo Violin/3 Effects/F SVL Trill WT.nki"
                                   #p"/Strings/Solo Violin/4 ModXfd/F SVL NV DXF.nki"
                                   #p"/Strings/Solo Violin/4 ModXfd/F SVL NV Vib DXF.nki"
                                   #p"/Strings/Solo Violin/4 ModXfd/F SVL QLeg DXF RR.nki"
                                   #p"/Strings/Solo Violin/4 ModXfd/F SVL QLeg DXF.nki"
                                   #p"/Strings/Solo Violin/4 ModXfd/F SVL Vib DXF.nki"
                                   #p"/Strings/Solo Violin/5 Keysw/F SVL KS Shrt RR C0-F#0.nki"
                                   #p"/Strings/Solo Violin/5 Keysw/F SVL KS Sus C0-B0.nki"


                                   #p"/Woodwinds/3 Clarinets/1 Long/F 3Cl Legato.nki"
                                   #p"/Woodwinds/3 Clarinets/1 Long/f 3Cl Sus.nki"
                                   #p"/Woodwinds/3 Clarinets/2 Short/F 3Cl Stac rr x3.nki"
                                   #p"/Woodwinds/3 Clarinets/2 Short/F 3Cl Stac.nki"
                                   #p"/Woodwinds/3 Clarinets/4 ModXfd/F 3cl Sus DXF Acc Vel.nki"
                                   #p"/Woodwinds/3 Clarinets/4 ModXfd/F 3cl Sus DXF.nki"
                                   #p"/Woodwinds/3 Clarinets/4 ModXfd/F 3cl Sus X-Fade.nki"
                                   #p"/Woodwinds/3 Clarinets/5 Keysw/F 3CL KS Sus C0-B0.nki"

                                   #p"/Woodwinds/3 Flutes/1 Long/F 3FL Exp dim.nki"
                                   #p"/Woodwinds/3 Flutes/1 Long/F 3FL Legato.nki"
                                   #p"/Woodwinds/3 Flutes/1 Long/F 3FL Non Vib.nki"
                                   #p"/Woodwinds/3 Flutes/1 Long/F 3FL Sus FST.nki"
                                   #p"/Woodwinds/3 Flutes/1 Long/F 3FL Sus.nki"
                                   #p"/Woodwinds/3 Flutes/2 Short/F 3FL Stac x3.nki"
                                   #p"/Woodwinds/3 Flutes/2 Short/F 3FL Stac.nki"
                                   #p"/Woodwinds/3 Flutes/3 Effects/F 3FL GLiss L.nki"
                                   #p"/Woodwinds/3 Flutes/3 Effects/F 3FL GLiss S.nki"
                                   #p"/Woodwinds/3 Flutes/3 Effects/F 3FL Grace.nki"
                                   #p"/Woodwinds/3 Flutes/3 Effects/F 3FL Trill H.nki"
                                   #p"/Woodwinds/3 Flutes/3 Effects/F 3FL Trill W.nki"
                                   #p"/Woodwinds/3 Flutes/4 ModXfd/F 3FL Emotn DXF.nki"
                                   #p"/Woodwinds/3 Flutes/4 ModXfd/F 3FL Non Vib-Sus XF.nki"
                                   #p"/Woodwinds/3 Flutes/4 ModXfd/F 3FL Sus DXF aCC vEL.nki"
                                   #p"/Woodwinds/3 Flutes/4 ModXfd/F 3FL Sus DXF.nki"
                                   #p"/Woodwinds/3 Flutes/5 Keysw/F 3FL KS Sus C0-B0.nki"

                                   #p"/Woodwinds/3 Oboes/1 Long/F 3OB Exp.nki"
                                   #p"/Woodwinds/3 Oboes/1 Long/F 3OB Legato.nki"
                                   #p"/Woodwinds/3 Oboes/1 Long/F 3OB Non Vib.nki"
                                   #p"/Woodwinds/3 Oboes/1 Long/F 3Ob Sus ViB.nki"
                                   #p"/Woodwinds/3 Oboes/2 Short/F 3OB Stac rr x3.nki"
                                   #p"/Woodwinds/3 Oboes/2 Short/F 3OB Stac.nki"
                                   #p"/Woodwinds/3 Oboes/3 Effects/F 3OB Grace.nki"
                                   #p"/Woodwinds/3 Oboes/3 Effects/F 3OB Trill H.nki"
                                   #p"/Woodwinds/3 Oboes/3 Effects/F 3OB Trill W.nki"
                                   #p"/Woodwinds/3 Oboes/4 ModXfd/F 3OB DXF Sus Acc Vel.nki"
                                   #p"/Woodwinds/3 Oboes/4 ModXfd/F 3OB DXF Sus.nki"
                                   #p"/Woodwinds/3 Oboes/4 ModXfd/F 3OB Emotn DXF.nki"
                                   #p"/Woodwinds/3 Oboes/4 ModXfd/F 3Ob Non Vib-Sus XF.nki"
                                   #p"/Woodwinds/3 Oboes/5 Keysw/F 3OB KS Sus C0-B0.nki"

                                   #p"/Woodwinds/Solo Alto Flute/1 Long/F AFL Exp Legato Bright.nki"
                                   #p"/Woodwinds/Solo Alto Flute/1 Long/F AFL Exp Legato Lyric.nki"
                                   #p"/Woodwinds/Solo Alto Flute/1 Long/F AFL Exp Legato.nki"
                                   #p"/Woodwinds/Solo Alto Flute/1 Long/F AFL ExP.nki"
                                   #p"/Woodwinds/Solo Alto Flute/1 Long/F AFL Legato.nki"
                                   #p"/Woodwinds/Solo Alto Flute/1 Long/F AFL Non Vib.nki"
                                   #p"/Woodwinds/Solo Alto Flute/1 Long/F AFL Sus Vib.nki"
                                   #p"/Woodwinds/Solo Alto Flute/2 Short/F AFL Stac RR x3.nki"
                                   #p"/Woodwinds/Solo Alto Flute/2 Short/F AFL Stac.nki"
                                   #p"/Woodwinds/Solo Alto Flute/3 Effects/F AFL Run Up Dn.nki"
                                   #p"/Woodwinds/Solo Alto Flute/4 ModXfd/F AFL Exp DXF ACC.nki"
                                   #p"/Woodwinds/Solo Alto Flute/4 ModXfd/F AFL Exp DXF.nki"
                                   #p"/Woodwinds/Solo Alto Flute/4 ModXfd/F AFL Legato DXF ACC.nki"
                                   #p"/Woodwinds/Solo Alto Flute/4 ModXfd/F AFL NV Vib XFADE.nki"
                                   #p"/Woodwinds/Solo Alto Flute/5 Keysw/F AFL KS Sus C0-B0.nki"

                                   #p"/Woodwinds/Solo Bass Clarinet/1 Long/F BCL Exp Fast.nki"
                                   #p"/Woodwinds/Solo Bass Clarinet/1 Long/F BCL Exp.nki"
                                   #p"/Woodwinds/Solo Bass Clarinet/1 Long/F BCL Portato.nki"
                                   #p"/Woodwinds/Solo Bass Clarinet/1 Long/F BCL QLeg RR.nki"
                                   #p"/Woodwinds/Solo Bass Clarinet/1 Long/F BCL QLeg.nki"
                                   #p"/Woodwinds/Solo Bass Clarinet/1 Long/F BCL Sus.nki"
                                   #p"/Woodwinds/Solo Bass Clarinet/2 Short/F BCL Marcato.nki"
                                   #p"/Woodwinds/Solo Bass Clarinet/2 Short/F BCL Stac RR x3.nki"
                                   #p"/Woodwinds/Solo Bass Clarinet/2 Short/F BCL Stac.nki"
                                   #p"/Woodwinds/Solo Bass Clarinet/3 Effects/F BCL gl m.nki"
                                   #p"/Woodwinds/Solo Bass Clarinet/3 Effects/F BCL Key Clicks MOD RT.nki"
                                   #p"/Woodwinds/Solo Bass Clarinet/4 ModXfd/F BCL QLeg DXF RR.nki"
                                   #p"/Woodwinds/Solo Bass Clarinet/4 ModXfd/F BCL QLeg DXF.nki"
                                   #p"/Woodwinds/Solo Bass Clarinet/4 ModXfd/F BCL Sus Acc MOD.nki"
                                   #p"/Woodwinds/Solo Bass Clarinet/4 ModXfd/F BCL Sus DXF.nki"
                                   #p"/Woodwinds/Solo Bass Clarinet/5 Keysw/F BCL KS Sus C0-A0.nki"

                                   #p"/Woodwinds/Solo Bassoon/1 Long/F BSN Exp Long Crec.nki"
                                   #p"/Woodwinds/Solo Bassoon/1 Long/F BSN Exp Short.nki"
                                   #p"/Woodwinds/Solo Bassoon/1 Long/F BSN Forte.nki"
                                   #p"/Woodwinds/Solo Bassoon/1 Long/F BSN Non Vib.nki"
                                   #p"/Woodwinds/Solo Bassoon/1 Long/F BSN QLeg RR.nki"
                                   #p"/Woodwinds/Solo Bassoon/1 Long/F BSN QLeg.nki"
                                   #p"/Woodwinds/Solo Bassoon/1 Long/F BSN Sus Vib.nki"
                                   #p"/Woodwinds/Solo Bassoon/2 Short/F BSN Marc.nki"
                                   #p"/Woodwinds/Solo Bassoon/2 Short/F BSN Stac RR x3.nki"
                                   #p"/Woodwinds/Solo Bassoon/2 Short/F BSN Stac.nki"
                                   #p"/Woodwinds/Solo Bassoon/3 Effects/F BSN Gliss.nki"
                                   #p"/Woodwinds/Solo Bassoon/3 Effects/F BSN Trill HT.nki"
                                   #p"/Woodwinds/Solo Bassoon/3 Effects/F BSN Trill WT.nki"
                                   #p"/Woodwinds/Solo Bassoon/4 ModXfd/F BSN Sus Accent Mod.nki"
                                   #p"/Woodwinds/Solo Bassoon/4 ModXfd/F BSN Sus Vib DXF.nki"
                                   #p"/Woodwinds/Solo Bassoon/4 ModXfd/F BSN Vib Xfade.nki"
                                   #p"/Woodwinds/Solo Bassoon/5 Keysw/F BSN KS Sus C0-A0.nki"

                                   #p"/Woodwinds/Solo Clarinet/1 Long/F SCL Exp Fast.nki"
                                   #p"/Woodwinds/Solo Clarinet/1 Long/F SCL Exp Slow Crec.nki"
                                   #p"/Woodwinds/Solo Clarinet/1 Long/F SCL Non Vib.nki"
                                   #p"/Woodwinds/Solo Clarinet/1 Long/F SCL Portato.nki"
                                   #p"/Woodwinds/Solo Clarinet/1 Long/F SCL QLeg RR.nki"
                                   #p"/Woodwinds/Solo Clarinet/1 Long/F SCL QLeg.nki"
                                   #p"/Woodwinds/Solo Clarinet/2 Short/F 3Cl Stac.nki"
                                   #p"/Woodwinds/Solo Clarinet/2 Short/F SCL Marc.nki"
                                   #p"/Woodwinds/Solo Clarinet/2 Short/F SCL Stac RR x3.nki"
                                   #p"/Woodwinds/Solo Clarinet/2 Short/F SCL Stac.nki"
                                   #p"/Woodwinds/Solo Clarinet/3 Effects/F SCL 8va Run Dn.nki"
                                   #p"/Woodwinds/Solo Clarinet/3 Effects/F SCL 8va Run Up Dn.nki"
                                   #p"/Woodwinds/Solo Clarinet/3 Effects/F SCL 8va Run Up Fast.nki"
                                   #p"/Woodwinds/Solo Clarinet/3 Effects/F SCL 8va Run Up.nki"
                                   #p"/Woodwinds/Solo Clarinet/3 Effects/F SCL Grace Notes.nki"
                                   #p"/Woodwinds/Solo Clarinet/3 Effects/F SCL Key Clicks MOD RT.nki"
                                   #p"/Woodwinds/Solo Clarinet/3 Effects/F SCL Trill HT.nki"
                                   #p"/Woodwinds/Solo Clarinet/3 Effects/F SCL Trill WT.nki"
                                   #p"/Woodwinds/Solo Clarinet/4 ModXfd/F SCL QLeg DXF RR.nki"
                                   #p"/Woodwinds/Solo Clarinet/4 ModXfd/F SCL QLeg DXF.nki"
                                   #p"/Woodwinds/Solo Clarinet/4 ModXfd/F SCL Sus Accent Mod.nki"
                                   #p"/Woodwinds/Solo Clarinet/5 Keysw/F SCL KS Sus C0-B0.nki"

                                   #p"/Woodwinds/Solo Contrabasson/1 Long/F CTB Exp Short.nki"
                                   #p"/Woodwinds/Solo Contrabasson/1 Long/F CTB Exp.nki"
                                   #p"/Woodwinds/Solo Contrabasson/1 Long/F CTB Legato.nki"
                                   #p"/Woodwinds/Solo Contrabasson/1 Long/F CTB Port F.nki"
                                   #p"/Woodwinds/Solo Contrabasson/1 Long/F CTB Sus.nki"
                                   #p"/Woodwinds/Solo Contrabasson/2 Short/F CTB STAC RR x3.nki"
                                   #p"/Woodwinds/Solo Contrabasson/2 Short/F CTB STAC.nki"
                                   #p"/Woodwinds/Solo Contrabasson/3 Effects/F CTB GLiss.nki"
                                   #p"/Woodwinds/Solo Contrabasson/3 Effects/F CTB Grace.nki"
                                   #p"/Woodwinds/Solo Contrabasson/4 ModXfd/F CTB Sus Accent Mod.nki"
                                   #p"/Woodwinds/Solo Contrabasson/4 ModXfd/F CTB Vib DXF ACC.nki"
                                   #p"/Woodwinds/Solo Contrabasson/4 ModXfd/F CTB Vib DXF.nki"
                                   #p"/Woodwinds/Solo Contrabasson/5 Keysw/F CTB KS Sus C4-B4.nki"

                                   #p"/Woodwinds/Solo English Horn/1 Long/F EHN Exp.nki"
                                   #p"/Woodwinds/Solo English Horn/1 Long/F EHN Legato.nki"
                                   #p"/Woodwinds/Solo English Horn/1 Long/F EHN NEW LEGATO.nki"
                                   #p"/Woodwinds/Solo English Horn/1 Long/F EHn Non Vib.nki"
                                   #p"/Woodwinds/Solo English Horn/1 Long/F EHN Sus Vib.nki"
                                   #p"/Woodwinds/Solo English Horn/2 Short/F EHN Stac RR x3.nki"
                                   #p"/Woodwinds/Solo English Horn/2 Short/F EHN Stac.nki"
                                   #p"/Woodwinds/Solo English Horn/3 Effects/F EHN Fall.nki"
                                   #p"/Woodwinds/Solo English Horn/3 Effects/F EHN Gliss.nki"
                                   #p"/Woodwinds/Solo English Horn/3 Effects/F EHN Grace.nki"
                                   #p"/Woodwinds/Solo English Horn/3 Effects/F EHN Slide.nki"
                                   #p"/Woodwinds/Solo English Horn/4 ModXfd/F EHN Legato DXF.nki"
                                   #p"/Woodwinds/Solo English Horn/4 ModXfd/F EHN NV Vib DXF.nki"
                                   #p"/Woodwinds/Solo English Horn/4 ModXfd/F EHN NV Vib XFad.nki"
                                   #p"/Woodwinds/Solo English Horn/4 ModXfd/F EHN Sus Accent Mod.nki"
                                   #p"/Woodwinds/Solo English Horn/4 ModXfd/F EHN Vib DXF ACC.nki"
                                   #p"/Woodwinds/Solo English Horn/4 ModXfd/F EHN Vib DXF.nki"
                                   #p"/Woodwinds/Solo English Horn/5 Keysw/F EHN KS Sus C0-B0.nki"

                                   #p"/Woodwinds/Solo English Horn 2/1 Long/F EH2 Exp.nki"
                                   #p"/Woodwinds/Solo English Horn 2/1 Long/F EH2 Portato NV.nki"
                                   #p"/Woodwinds/Solo English Horn 2/1 Long/F EH2 QLeg RR.nki"
                                   #p"/Woodwinds/Solo English Horn 2/1 Long/F EH2 QLeg.nki"
                                   #p"/Woodwinds/Solo English Horn 2/1 Long/F EH2 Sus.nki"
                                   #p"/Woodwinds/Solo English Horn 2/2 Short/F EH2 Stac RR x3.nki"
                                   #p"/Woodwinds/Solo English Horn 2/2 Short/F EH2 Stac.nki"
                                   #p"/Woodwinds/Solo English Horn 2/3 Effects/F EH2 Grace Notes.nki"
                                   #p"/Woodwinds/Solo English Horn 2/3 Effects/F EH2 Trill HT.nki"
                                   #p"/Woodwinds/Solo English Horn 2/3 Effects/F EH2 Trill WT.nki"
                                   #p"/Woodwinds/Solo English Horn 2/4 ModXfd/F EH2 QLeg DXF RR.nki"
                                   #p"/Woodwinds/Solo English Horn 2/4 ModXfd/F EH2 QLeg DXF.nki"
                                   #p"/Woodwinds/Solo English Horn 2/4 ModXfd/F EH2 Sus Acc Mod.nki"
                                   #p"/Woodwinds/Solo English Horn 2/4 ModXfd/F EH2 Sus DXF.nki"
                                   #p"/Woodwinds/Solo English Horn 2/5 Keysw/F EH2 KS Sus C0-B0.nki"

                                   #p"/Woodwinds/Solo Flute/1 Long/F SFL Exp Legato.nki"
                                   #p"/Woodwinds/Solo Flute/1 Long/F SFL Lyrical.nki"
                                   #p"/Woodwinds/Solo Flute/1 Long/F SFL Non Vib.nki"
                                   #p"/Woodwinds/Solo Flute/1 Long/F SFL QLeg RR.nki"
                                   #p"/Woodwinds/Solo Flute/1 Long/F SFL QLeg.nki"
                                   #p"/Woodwinds/Solo Flute/1 Long/F SFL Sforzando Vib.nki"
                                   #p"/Woodwinds/Solo Flute/1 Long/F SFL Slow exp 2.nki"
                                   #p"/Woodwinds/Solo Flute/1 Long/F SFL Slow EXP.nki"
                                   #p"/Woodwinds/Solo Flute/1 Long/F SFL Sus NV PPP.nki"
                                   #p"/Woodwinds/Solo Flute/1 Long/F SFL Sus Vib Bright.nki"
                                   #p"/Woodwinds/Solo Flute/1 Long/F SFL Sus Vib.nki"
                                   #p"/Woodwinds/Solo Flute/2 Short/F SFL Short Stac RR x2.nki"
                                   #p"/Woodwinds/Solo Flute/2 Short/F SFL Short Stac.nki"
                                   #p"/Woodwinds/Solo Flute/2 Short/F SFL Stac RR x3.nki"
                                   #p"/Woodwinds/Solo Flute/2 Short/F SFL Stac.nki"
                                   #p"/Woodwinds/Solo Flute/3 Effects/F SFL 8va Run Dn.nki"
                                   #p"/Woodwinds/Solo Flute/3 Effects/F SFL 8va Run Up Dn.nki"
                                   #p"/Woodwinds/Solo Flute/3 Effects/F SFL 8va Run Up.nki"
                                   #p"/Woodwinds/Solo Flute/3 Effects/F SFL Fall.nki"
                                   #p"/Woodwinds/Solo Flute/3 Effects/F SFL Flutter Mod.nki"
                                   #p"/Woodwinds/Solo Flute/3 Effects/F SFL Grace.nki"
                                   #p"/Woodwinds/Solo Flute/3 Effects/F SFL Psycho Run Dn RR.nki"
                                   #p"/Woodwinds/Solo Flute/3 Effects/F SFL Trill HT.nki"
                                   #p"/Woodwinds/Solo Flute/3 Effects/F SFL Trill WT.nki"
                                   #p"/Woodwinds/Solo Flute/4 ModXfd/F SFL Accent Mod.nki"
                                   #p"/Woodwinds/Solo Flute/4 ModXfd/F SFL Lush Accent Mod.nki"
                                   #p"/Woodwinds/Solo Flute/4 ModXfd/F SFL QLeg DXF RR.nki"
                                   #p"/Woodwinds/Solo Flute/4 ModXfd/F SFL QLeg DXF.nki"
                                   #p"/Woodwinds/Solo Flute/4 ModXfd/F SFL Vib DXF 2 ACC.nki"
                                   #p"/Woodwinds/Solo Flute/4 ModXfd/F SFL Vib DXF 2.nki"
                                   #p"/Woodwinds/Solo Flute/4 ModXfd/F SFL Vib DXF.nki"
                                   #p"/Woodwinds/Solo Flute/5 Keysw/F SFL KS Sus C0-B0.nki"

                                   #p"/Woodwinds/Solo Oboe/1 Long/F SOB Exp P.nki"
                                   #p"/Woodwinds/Solo Oboe/1 Long/F SOB Exp Vib.nki"
                                   #p"/Woodwinds/Solo Oboe/1 Long/F SOB Non Vib.nki"
                                   #p"/Woodwinds/Solo Oboe/1 Long/F SOB QLeg RR.nki"
                                   #p"/Woodwinds/Solo Oboe/1 Long/F SOB QLeg.nki"
                                   #p"/Woodwinds/Solo Oboe/1 Long/F SOB Sfz.nki"
                                   #p"/Woodwinds/Solo Oboe/1 Long/F SOB Sus Vib.nki"
                                   #p"/Woodwinds/Solo Oboe/2 Short/F SOB Stac RR x3.nki"
                                   #p"/Woodwinds/Solo Oboe/2 Short/F SOB Stac.nki"
                                   #p"/Woodwinds/Solo Oboe/3 Effects/F SOB Fall.nki"
                                   #p"/Woodwinds/Solo Oboe/3 Effects/F SOB Gliss.nki"
                                   #p"/Woodwinds/Solo Oboe/3 Effects/F SOB Grace.nki"
                                   #p"/Woodwinds/Solo Oboe/3 Effects/F SOB Key Clicks MOD RT.nki"
                                   #p"/Woodwinds/Solo Oboe/3 Effects/F SOB Trill H.nki"
                                   #p"/Woodwinds/Solo Oboe/3 Effects/F SOB Trill W.nki"
                                   #p"/Woodwinds/Solo Oboe/4 ModXfd/F SOB NV Vib DXF.nki"
                                   #p"/Woodwinds/Solo Oboe/4 ModXfd/F SOB QLeg DXF RR.nki"
                                   #p"/Woodwinds/Solo Oboe/4 ModXfd/F SOB QLeg DXF.nki"
                                   #p"/Woodwinds/Solo Oboe/4 ModXfd/F SOB Sus Acc Mod.nki"
                                   #p"/Woodwinds/Solo Oboe/5 Keysw/F SOB KS Sus C0-B0.nki"

                                   #p"/Woodwinds/Solo Piccolo Flute/1 Long/F PFL Exp.nki"
                                   #p"/Woodwinds/Solo Piccolo Flute/1 Long/F PFL QLeg RR.nki"
                                   #p"/Woodwinds/Solo Piccolo Flute/1 Long/F PFL QLeg.nki"
                                   #p"/Woodwinds/Solo Piccolo Flute/1 Long/F PFL Sus NV PPP.nki"
                                   #p"/Woodwinds/Solo Piccolo Flute/1 Long/F PFL Sus Vib.nki"
                                   #p"/Woodwinds/Solo Piccolo Flute/1 Long/S Pfl Sus Vib.nki"
                                   #p"/Woodwinds/Solo Piccolo Flute/2 Short/F Pfl Stac RR x3.nki"
                                   #p"/Woodwinds/Solo Piccolo Flute/2 Short/F Pfl Stac.nki"
                                   #p"/Woodwinds/Solo Piccolo Flute/3 Effects/F PFL 8va Dn.nki"
                                   #p"/Woodwinds/Solo Piccolo Flute/3 Effects/F PFL 8va Up Dn.nki"
                                   #p"/Woodwinds/Solo Piccolo Flute/3 Effects/F PFL 8va Up.nki"
                                   #p"/Woodwinds/Solo Piccolo Flute/3 Effects/F Pfl Gliss.nki"
                                   #p"/Woodwinds/Solo Piccolo Flute/3 Effects/F PFL Psycho fall Fst.nki"
                                   #p"/Woodwinds/Solo Piccolo Flute/3 Effects/F PFL Rips Up 3rd.nki"
                                   #p"/Woodwinds/Solo Piccolo Flute/3 Effects/F PFL Rips Up 5th.nki"
                                   #p"/Woodwinds/Solo Piccolo Flute/3 Effects/F PFL Rips WT.nki"
                                   #p"/Woodwinds/Solo Piccolo Flute/3 Effects/F PFL Trill H.nki"
                                   #p"/Woodwinds/Solo Piccolo Flute/3 Effects/F PFL Trill W.nki"
                                   #p"/Woodwinds/Solo Piccolo Flute/4 ModXfd/F PFL Sus Accent Mod.nki"
                                   #p"/Woodwinds/Solo Piccolo Flute/4 ModXfd/F PfL Vib DXF ACC.nki"
                                   #p"/Woodwinds/Solo Piccolo Flute/4 ModXfd/F PfL Vib DXF.nki"
                                   #p"/Woodwinds/Solo Piccolo Flute/5 Keysw/F PFL KS FX C0-G0.nki"
                                   #p"/Woodwinds/Solo Piccolo Flute/5 Keysw/F PFL KS Sus C0-B0.nki"))

;;; has to be harp solo (optional) psycho effects

(defun sort-pathnames(patterns)
  (sort (iter (for file in *ALL-EWQLSO-FILES*)
          (for filename = (string-downcase (namestring file)))
          (collect
           (cons file
                 (iter
                   (for pattern in patterns)
                   (for match-p = (if (stringp pattern)
                                      (ppcre::scan (string-downcase pattern) filename)
                                    (ppcre::scan (string-downcase (car pattern)) filename)))
                   (when match-p
                     (summing (if (stringp pattern)
                                  1
                                (cdr pattern))))))))
        '>
        :key #'cdr))

;;; (sort-pathnames '("Bass Clarinet"))
;;; (car (sort-pathnames '(("Bass Clarinet" . 10000))))

;;; (ppcre::scan "Bass Clarinet" "/Woodwinds/Solo Bass Clarinet/1 Long/F BCL QLeg RR.nki")

(defun update-regex-scanner(interface)
  (with-slots (instrument-regex expression-regexs regexs result-pane) interface
    (let ((patterns (append
                     (list (cons (capi:text-input-pane-text instrument-regex) 100000))
                     (remove-if #'empty-string-p (read-all-from-string (capi:text-input-pane-text expression-regexs))))))
      (setf (capi:text-input-pane-text regexs) (format () "~s" patterns))
      (setf (capi:collection-items result-pane) (sort-pathnames patterns)))))

(capi:define-interface regex-scanner ()
  ()
  (:panes
   (navigator-pane capi::list-panel
                   :items (EWQLSO-orchestra-browser-items)
                   :print-function #'name
                   :selection-callback #'(lambda(item interface)
                                           (with-slots (instrument-regex) interface
                                             (setf (capi:text-input-pane-text instrument-regex) (name item))
                                             (update-regex-scanner interface))))
                                             
   (instrument-regex capi:text-input-pane :text "" :title "instrument" :title-position :top
                     :change-callback-type :interface
                     :change-callback 'update-regex-scanner)
                                         
   (expression-regexs capi:text-input-pane :text "" :title "expressions" :title-position :top
                      :change-callback-type :interface
                      :change-callback 'update-regex-scanner)

   (regexs capi:text-input-pane :text "")

   (result-pane capi:multi-column-list-panel 
                :columns '((:title "Weigth" :visible-min-width 32) (:title "Sample"))
                :column-function #'(lambda(x) (list (cdr x) (car x)))))
  (:default-initargs
   :width 700
   :height 900))

(capi:find-interface 'regex-scanner)