
(IN-PACKAGE :CCL)

(DEFMETHOD SYSTEM::NKI
  ((SYSTEM::SELF SYSTEM::ALTO-FLUTE)
   (TYPE T)
   (SYSTEM::EXPRESSION STACCATO))
  #P"14 Alto flute/nki/AFL_stac_basic.nki")

(DEFMETHOD SYSTEM::NKI
  ((SYSTEM::SELF SYSTEM::ALTO-FLUTE) (TYPE T) (SYSTEM::EXPRESSION SFZ))
  #P"14 Alto flute/nki/AFL_mV_sfz_basic.nki")
