
(IN-PACKAGE :CCL)

(DEFMETHOD SYSTEM::NKI
  ((SYSTEM::SELF SYSTEM::FLUTE) (TYPE T) (SYSTEM::EXPRESSION STACCATO))
  #P"12 Flute-1/nki/FL1_stac-1.nki")


(DEFMETHOD SYSTEM::NKI
  ((SYSTEM::SELF SYSTEM::FLUTE) (TYPE T) (SYSTEM::EXPRESSION TREMOLO))
  #P"12 Flute-1/nki/FL1_flatter.nki")

(DEFMETHOD SYSTEM::NKI
  ((SYSTEM::SELF SYSTEM::FLUTE) (TYPE T) (SYSTEM::EXPRESSION SFZ))
  #P"12 Flute-1/nki/FL1-B_sfz.nki")

(DEFMETHOD SYSTEM::NKI
  ((SYSTEM::SELF SYSTEM::FLUTE)
   (TYPE T)
   (SYSTEM::EXPRESSION SYSTEM::EXPRESSION))
  (COND ((CL-PPCRE:SCAN "flutter*"
                        (SYSTEM::PRINT-SYMBOL SYSTEM::EXPRESSION))
         #P"12 Flute-1/nki/FL1_flatter.nki")))