
(IN-PACKAGE :CCL)

(DEFMETHOD SYSTEM::NKI
  ((SYSTEM::SELF SYSTEM::OBOE) (TYPE T) (SYSTEM::EXPRESSION STACCATO))
  #P"15 Oboe/nki/OB_stac_basic.nki")

(DEFMETHOD SYSTEM::NKI
  ((SYSTEM::SELF SYSTEM::OBOE) (TYPE T) (SYSTEM::EXPRESSION SFZ))
  #P"15 Oboe/nki/OB_sfz_basic.nki")
