
(IN-PACKAGE :CCL)

(DEFMETHOD SYSTEM::NKI
  ((SYSTEM::SELF SYSTEM::FRENCH-HORN)
   (TYPE T)
   (SYSTEM::EXPRESSION STACCATO))
  #P"26 Horn/nki/HO_stac_nA_basic.nki")

(DEFMETHOD SYSTEM::NKI
  ((SYSTEM::SELF SYSTEM::FRENCH-HORN)
   (TYPE T)
   (SYSTEM::EXPRESSION SFZ))
  #P"26 Horn/nki/HO_oV_sfz_basic.nki")
