
(IN-PACKAGE :CCL)

(DEFMETHOD SYSTEM::NKI
  ((SYSTEM::SELF SYSTEM::TUBA) (TYPE T) (SYSTEM::EXPRESSION STACCATO))
  #P"32 Tuba/nki/TU_stac_basic.nki")

(DEFMETHOD SYSTEM::NKI
  ((SYSTEM::SELF SYSTEM::TUBA) (TYPE T) (SYSTEM::EXPRESSION SFZ))
  #P"32 Tuba/nki/TU_oV_sfz_basic.nki")
