
(IN-PACKAGE :CCL)

(DEFMETHOD NKI
  ((SELF FRENCH-HORN-IN-EB) (TYPE T) (EXPRESSION STACCATO))
  #P"Brass/Solo French Horn/2 Short/F SFH Stac RR.nki")

(DEFMETHOD NKI
  ((SELF FRENCH-HORN-IN-EB) (TYPE T) (EXPRESSION ACCENT))
  #P"Brass/Solo French Horn/2 Short/F SFH Marc.nki")

(DEFMETHOD NKI
  ((SELF FRENCH-HORN-IN-EB) (TYPE T) (EXPRESSION SFZ))
  #P"Brass/Solo French Horn/1 Long/F SFH Sfz Crec.nki")

(DEFMETHOD NKI
  ((SELF FRENCH-HORN-IN-EB) (TYPE T) (EXPRESSION SLUR))
  #P"Brass/Solo French Horn/1 Long/F SFH QLeg.nki")

(DEFMETHOD NKI
  ((SELF FRENCH-HORN-IN-EB) (TYPE T) (EXPRESSION SLUR))
  #P"Brass/Solo French Horn/1 Long/F SFH QLeg.nki")
